### ISSUE TITLE
Blocks not rendering some sides

### ISSUE THREAD

**Issue by smithnc07** [elucent/Blockcraftery#1]
Good morning! I Love the mod. 

I was just poking at it to do some testing and found there are a few instances where a block isn't rendering a side. These are as follows:

Normal stairs: bottom of the stairs, on the back half.
Upside down stairs: The 'top' of the [upside down] steps.
Wall: Bottom.
Double-slab: Bottom

Thank you for your work!

**Comment by elucent** [comment]
Oh, whoops. Sorry about that, I should have a fix. Will only require an update in EluLib actually.

**Comment by elucent** [comment]
![image](https://user-images.githubusercontent.com/9532786/30918481-adc21cb6-a36c-11e7-818e-57bd2a8395b9.png)

Should be fixed! Will post an update soon. Sorry, got a little sloppy with my UV. xD

**Comment by smithnc07** [comment]
Ha, no problem at all. Thanks for the Fix!

**Comment by elucent** [comment]
In theory, the fix should be getting approved on CurseForge as we speak. Closing this.

**Comment by smithnc07** [comment]
Confirmed Fixed.
