### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by digi-tal-it** [elucent/Blockcraftery#7]
Hi,

just wanted to tell you, that I have a recipe conflict with Applied Energistics. They use the same recipe as your framed block, so I can't craft it. 

https://imgur.com/a/JYIlw

**Comment by digi-tal-it** [comment]
I saw, that buildcraft also uses the same recipe for its wooden gear.

**Comment by elucent** [comment]
I'll change it but this is a difficult issue to fix, considering that these blocks really need a very simple and intuitive recipe.

**Comment by elucent** [comment]
Changed to four sticks in the corners. This should have less conflicts.

**Comment by elucent** [comment]
Will be in next version.

**Comment by trogarus** [comment]
This is a thing, and should be part of any standard modpack. https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict
