### ISSUE TITLE
Filled Frames Still Consume Item

### ISSUE THREAD

**Issue by ChloeDawn** [elucent/Blockcraftery#8]
**Mod version:** [0.1.2](https://minecraft.curseforge.com/projects/blockcraftery/files/2484974)
**Forge version:** [1.12.2-14.23.0.2491](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2491/forge-1.12.2-14.23.0.2491-changelog.txt)

Frames allow you to place blocks inside them when they already contain a block, in turn nullifying the previous frame contents.

**Comment by elucent** [comment]
Fixed.
