### ISSUE TITLE
Particle Texture Inheriting Tint Index

### ISSUE THREAD

**Issue by ChloeDawn** [elucent/Blockcraftery#9]
**Mod version:** [0.1.2](https://minecraft.curseforge.com/projects/blockcraftery/files/2484974)
**Forge version:** [1.12.2-14.23.0.2491](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2491/forge-1.12.2-14.23.0.2491-changelog.txt)

The frame's particle texture inherits the tint index of the contained block model.

**Comment by elucent** [comment]
Yeah this isn't something I'm going to fix. It's a tiny tiny issue, tint indices are dynamically decided wholly based off of the source model, and I can neither modify the particle texture nor do I handle the particle spawning. Fixing this is more trouble than it's worth.
